In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/shamnad-sherief/datasets/main/50_Startups.csv')

In [5]:
x = dataset.iloc[:,:4].values

In [6]:
y = dataset.iloc[:,4:5].values

In [7]:
# Converting type of columns to category
dataset['State']=dataset['State'].astype('category')

In [8]:
#Assigning numerical values and storing it in another columns
dataset['Stat_new']=dataset['State'].cat.codes

In [9]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42     Florida  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68     Florida  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95     Florida  146121.95   
11  100671.96        91790.61        249744.55  California  144259.40   
12   93863.75       127320.38        249839.44     Florida  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57     Florida  124266.90   
19   86419.70       153514.11             0.00    New York  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26     Florida  110352.25   
23   67532.53       105751.03        304768.73     Florida  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07     Florida  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24     Florida   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81     Florida   96778.92   
34   46426.07       157693.92        210797.67  California   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82     Florida   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67  California   78239.91   
41   27892.92        84710.77        164470.71     Florida   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

    Stat_new  
0          2  
1          0  
2          1  
3          2  
4          1  
5          2  
6          0  
7          1  
8          2  
9          0  
10         1  
11         0  
12         1  
13         0  
14         1  
15         2  
16         0  
17        

In [10]:
#Create an instance of One-hot-encoder
enc=OneHotEncoder()

In [11]:
#Passing encoded columns
enc_data=pd.DataFrame(enc.fit_transform(dataset[['Stat_new']]).toarray())

In [12]:
enc_data

0    1    2
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  0.0  1.0
4   0.0  1.0  0.0
5   0.0  0.0  1.0
6   1.0  0.0  0.0
7   0.0  1.0  0.0
8   0.0  0.0  1.0
9   1.0  0.0  0.0
10  0.0  1.0  0.0
11  1.0  0.0  0.0
12  0.0  1.0  0.0
13  1.0  0.0  0.0
14  0.0  1.0  0.0
15  0.0  0.0  1.0
16  1.0  0.0  0.0
17  0.0  0.0  1.0
18  0.0  1.0  0.0
19  0.0  0.0  1.0
20  1.0  0.0  0.0
21  0.0  0.0  1.0
22  0.0  1.0  0.0
23  0.0  1.0  0.0
24  0.0  0.0  1.0
25  1.0  0.0  0.0
26  0.0  1.0  0.0
27  0.0  0.0  1.0
28  0.0  1.0  0.0
29  0.0  0.0  1.0
30  0.0  1.0  0.0
31  0.0  0.0  1.0
32  1.0  0.0  0.0
33  0.0  1.0  0.0
34  1.0  0.0  0.0
35  0.0  0.0  1.0
36  0.0  1.0  0.0
37  1.0  0.0  0.0
38  0.0  0.0  1.0
39  1.0  0.0  0.0
40  1.0  0.0  0.0
41  0.0  1.0  0.0
42  1.0  0.0  0.0
43  0.0  0.0  1.0
44  1.0  0.0  0.0
45  0.0  0.0  1.0
46  0.0  1.0  0.0
47  1.0  0.0  0.0
48  0.0  0.0  1.0
49  1.0  0.0  0.0

In [13]:
#Merge with main
New_df=dataset.join(enc_data)

In [14]:
New_df

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42     Florida  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68     Florida  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95     Florida  146121.95   
11  100671.96        91790.61        249744.55  California  144259.40   
12   93863.75       127320.38        249839.44     Florida  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57     Florida  124266.90   
19   86419.70       153514.11             0.00    New York  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26     Florida  110352.25   
23   67532.53       105751.03        304768.73     Florida  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07     Florida  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24     Florida   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81     Florida   96778.92   
34   46426.07       157693.92        210797.67  California   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82     Florida   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67  California   78239.91   
41   27892.92        84710.77        164470.71     Florida   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

    Stat_new    0    1    2  
0          2  0.0  0.0  1.0  
1          0  1.0  0.0  0.0  
2          1  0.0  1.0  0.0  
3          2  0.0  0.0  1.0  
4          1  0.0  1.0  0.0  
5          2  0.0  0.0  1.0  
6          0  1.0  0.0  0.0  
7          1  0.0  1.0  0.0  
8         

In [15]:
one_hot_encoded_data = pd.get_dummies(dataset, columns = ['State'])
print(one_hot_encoded_data)

    R&D Spend  Administration  Marketing Spend     Profit  Stat_new  \
0   165349.20       136897.80        471784.10  192261.83         2   
1   162597.70       151377.59        443898.53  191792.06         0   
2   153441.51       101145.55        407934.54  191050.39         1   
3   144372.41       118671.85        383199.62  182901.99         2   
4   142107.34        91391.77        366168.42  166187.94         1   
5   131876.90        99814.71        362861.36  156991.12         2   
6   134615.46       147198.87        127716.82  156122.51         0   
7   130298.13       145530.06        323876.68  155752.60         1   
8   120542.52       148718.95        311613.29  152211.77         2   
9   123334.88       108679.17        304981.62  149759.96         0   
10  101913.08       110594.11        229160.95  146121.95         1   
11  100671.96        91790.61        249744.55  144259.40         0   
12   93863.75       127320.38        249839.44  141585.52         1   
13   9

In [16]:
x_variable = New_df.drop(New_df.columns[[3]], axis = 1)

In [17]:
x_variable = New_df.drop(["State", "Stat_new"], axis = 1)

In [18]:
x_variable

R&D Spend  Administration  Marketing Spend     Profit    0    1    2
0   165349.20       136897.80        471784.10  192261.83  0.0  0.0  1.0
1   162597.70       151377.59        443898.53  191792.06  1.0  0.0  0.0
2   153441.51       101145.55        407934.54  191050.39  0.0  1.0  0.0
3   144372.41       118671.85        383199.62  182901.99  0.0  0.0  1.0
4   142107.34        91391.77        366168.42  166187.94  0.0  1.0  0.0
5   131876.90        99814.71        362861.36  156991.12  0.0  0.0  1.0
6   134615.46       147198.87        127716.82  156122.51  1.0  0.0  0.0
7   130298.13       145530.06        323876.68  155752.60  0.0  1.0  0.0
8   120542.52       148718.95        311613.29  152211.77  0.0  0.0  1.0
9   123334.88       108679.17        304981.62  149759.96  1.0  0.0  0.0
10  101913.08       110594.11        229160.95  146121.95  0.0  1.0  0.0
11  100671.96        91790.61        249744.55  144259.40  1.0  0.0  0.0
12   93863.75       127320.38        249839.44  141585.52  0.0  1.0  0.0
13   91992.39       135495.07        252664.93  134307.35  1.0  0.0  0.0
14  119943.24       156547.42        256512.92  132602.65  0.0  1.0  0.0
15  114523.61       122616.84        261776.23  129917.04  0.0  0.0  1.0
16   78013.11       121597.55        264346.06  126992.93  1.0  0.0  0.0
17   94657.16       145077.58        282574.31  125370.37  0.0  0.0  1.0
18   91749.16       114175.79        294919.57  124266.90  0.0  1.0  0.0
19   86419.70       153514.11             0.00  122776.86  0.0  0.0  1.0
20   76253.86       113867.30        298664.47  118474.03  1.0  0.0  0.0
21   78389.47       153773.43        299737.29  111313.02  0.0  0.0  1.0
22   73994.56       122782.75        303319.26  110352.25  0.0  1.0  0.0
23   67532.53       105751.03        304768.73  108733.99  0.0  1.0  0.0
24   77044.01        99281.34        140574.81  108552.04  0.0  0.0  1.0
25   64664.71       139553.16        137962.62  107404.34  1.0  0.0  0.0
26   75328.87       144135.98        134050.07  105733.54  0.0  1.0  0.0
27   72107.60       127864.55        353183.81  105008.31  0.0  0.0  1.0
28   66051.52       182645.56        118148.20  103282.38  0.0  1.0  0.0
29   65605.48       153032.06        107138.38  101004.64  0.0  0.0  1.0
30   61994.48       115641.28         91131.24   99937.59  0.0  1.0  0.0
31   61136.38       152701.92         88218.23   97483.56  0.0  0.0  1.0
32   63408.86       129219.61         46085.25   97427.84  1.0  0.0  0.0
33   55493.95       103057.49        214634.81   96778.92  0.0  1.0  0.0
34   46426.07       157693.92        210797.67   96712.80  1.0  0.0  0.0
35   46014.02        85047.44        205517.64   96479.51  0.0  0.0  1.0
36   28663.76       127056.21        201126.82   90708.19  0.0  1.0  0.0
37   44069.95        51283.14        197029.42   89949.14  1.0  0.0  0.0
38   20229.59        65947.93        185265.10   81229.06  0.0  0.0  1.0
39   38558.51        82982.09        174999.30   81005.76  1.0  0.0  0.0
40   28754.33       118546.05        172795.67   78239.91  1.0  0.0  0.0
41   27892.92        84710.77        164470.71   77798.83  0.0  1.0  0.0
42   23640.93        96189.63        148001.11   71498.49  1.0  0.0  0.0
43   15505.73       127382.30         35534.17   69758.98  0.0  0.0  1.0
44   22177.74       154806.14         28334.72   65200.33  1.0  0.0  0.0
45    1000.23       124153.04          1903.93   64926.08  0.0  0.0  1.0
46    1315.46       115816.21        297114.46   49490.75  0.0  1.0  0.0
47       0.00       135426.92             0.00   42559.73  1.0  0.0  0.0
48     542.05        51743.15             0.00   35673.41  0.0  0.0  1.0
49       0.00       116983.80         45173.06   14681.40  1.0  0.0  0.0

In [19]:
from pandas.core.common import random_state
#spiltting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_variable, y, test_size= 0.3)

In [20]:
# Fitting the model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,


LinearRegression()

In [21]:
y_pred = regressor.predict(x_test)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,


In [22]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)

In [23]:
score

1.0

In [24]:
regressor.coef_

array([[-8.04463069e-16,  0.00000000e+00,  1.66533454e-16,
         1.00000000e+00,  1.10596698e-12, -1.56288477e-12,
         4.56917802e-13]])

In [25]:
regressor.intercept_


array([-1.45519152e-11])

In [26]:
import pickle
# create an iterator object with write permission - model.pkl
with open('model_pkl', 'wb') as files:
    pickle.dump(regressor, files)

In [27]:
# load saved model
with open('model_pkl' , 'rb') as f:
    lr = pickle.load(f)

In [28]:
x_test.values

array([[1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 1.5699112e+05,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [7.2107600e+04, 1.2786455e+05, 3.5318381e+05, 1.0500831e+05,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [4.6014020e+04, 8.5047440e+04, 2.0551764e+05, 9.6479510e+04,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 9.7427840e+04,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [2.7892920e+04, 8.4710770e+04, 1.6447071e+05, 7.7798830e+04,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 1.5221177e+05,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [7.3994560e+04, 1.2278275e+05, 3.0331926e+05, 1.1035225e+05,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [1.3154600e+03, 1.1581621e+05, 2.9711446e+05, 4.9490750e+04,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [2.8663760e+04, 1

In [29]:
z=[6.4664710e+04, 1.3955316e+05, 1.3796262e+05, 1.0740434e+05,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00]

In [30]:
lr.predict([z])

array([[107404.34]])